### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by alexey62soft** [AlexandrYanochkin/YanochkinAlexandr_dotNet#1]
Please, add the report of Lab 1 to the repository.

**Comment by AlexandrYanochkin** [comment]
Good evening!!! what exactly should contain the report?

пт, 3 апр. 2020 г. в 23:54, Aliaksei Rakitski <notifications@github.com>:

**Comment by alexey62soft** [comment]
Sent via telegram.

**Comment by AlexandrYanochkin** [comment]
The report has added to sic.labs.first folder
